# Generated by Django 6.0.1 on 2026-01-31 10:04

import infoweb.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[infoweb.validators.email_validator],
            ),
        ),
    ]
