# Generated by Django 6.0.3 on 2026-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoweb", "0004_contact_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
