# Generated by Django 6.0.3 on 2026-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoweb", "0005_user_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="business",
            field=models.CharField(
                choices=[
                    ("produce", "Fresh Produce & Wholesale"),
                    ("ecommerce", "E-Commerce Partnership"),
                    ("services", "Business Services"),
                    ("apparel", "Fashion & Apparel"),
                    ("other", "Other Inquiry"),
                ],
                max_length=20,
            ),
        ),
    ]
