# Generated by Django 6.0.3 on 2026-04-14 17:30

import infoweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoweb", "0006_alter_collection_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=infoweb.models.collection_upload_path
            ),
        ),
    ]
