[build]
builder = "dockerfile"

[deploy]
startCommand = "mkdir -p backend/media && cd backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"